/**
 * Blackout Secure Sitemap Generator
 * Copyright © 2025-2026 Blackout Secure
 * SPDX-License-Identifier: Apache-2.0
 *
 * PROJECT CONFIGURATION (MAINTAINER ONLY)
 *
 * This file contains project metadata and branding information.
 * These values are controlled by the copyright holder and should NOT be
 * modified by contributors or end users. For user-configurable settings,
 * see action.yml inputs instead.
 *
 * WARNING: Modifying these values may violate license terms and attribution
 * requirements. Only the copyright holder (Blackout Secure) should edit this file.
 */

/**
 * Project metadata and branding configuration
 * @private - For internal use only
 */
const PROJECT_CONFIG = {
  // Project identity
  name: 'Blackout Secure Sitemap Generator',
  version: '0.1.0',

  // Copyright and licensing
  copyrightYearStart: '2025',
  copyrightYearEnd: '2026',
  copyrightHolder: 'Blackout Secure',
  license: 'Apache License 2.0',
  spdxIdentifier: 'Apache-2.0',

  // Repository information
  repository: {
    owner: 'blackoutmode',
    name: 'bos-sitemap-generator',
    url: 'github.com/blackoutmode/bos-sitemap-generator',
    issuesUrl: 'github.com/blackoutmode/bos-sitemap-generator/issues',
  },

  // Generated file attribution
  generatedByComment: 'generated by Blackout Secure Sitemap Generator',

  // Display preferences
  showBranding: true,
  brandingEmoji: '🗺️',
};

/**
 * Get formatted copyright notice
 * @returns {string} Copyright notice string
 */
function getCopyrightNotice() {
  const { copyrightYearStart, copyrightYearEnd, copyrightHolder, license } =
    PROJECT_CONFIG;
  const yearRange =
    copyrightYearStart === copyrightYearEnd
      ? copyrightYearStart
      : `${copyrightYearStart}-${copyrightYearEnd}`;
  return `© ${yearRange} ${copyrightHolder} | ${license}`;
}

/**
 * Get formatted project title
 * @returns {string} Project title with emoji
 */
function getProjectTitle() {
  return `${PROJECT_CONFIG.brandingEmoji}  ${PROJECT_CONFIG.name} v${PROJECT_CONFIG.version}`;
}

/**
 * Get repository URL
 * @returns {string} Repository URL
 */
function getRepositoryUrl() {
  return `📦 ${PROJECT_CONFIG.repository.url}`;
}

/**
 * Get support/issues URL
 * @returns {string} Issues URL
 */
function getSupportUrl() {
  return `💬 Support: ${PROJECT_CONFIG.repository.issuesUrl}`;
}

/**
 * Get file generation comment
 * @param {string} fileType - Type of file (e.g., 'sitemap.xml')
 * @returns {string} Generation comment
 */
function getGenerationComment(fileType) {
  return `# ${fileType} ${PROJECT_CONFIG.generatedByComment}`;
}

/**
 * Get detailed generation header for XML files
 * @returns {string} XML comment header with tool info
 */
function getXmlGenerationHeader() {
  const {
    name,
    version,
    repository,
    copyrightHolder,
    copyrightYearStart,
    copyrightYearEnd,
    license,
    spdxIdentifier,
  } = PROJECT_CONFIG;
  const yearRange =
    copyrightYearStart === copyrightYearEnd
      ? copyrightYearStart
      : `${copyrightYearStart}-${copyrightYearEnd}`;

  return `<!--
  Generated by: ${name} v${version}
  Copyright: © ${yearRange} ${copyrightHolder}
  License: ${license}
  SPDX-License-Identifier: ${spdxIdentifier}
  Repository: https://${repository.url}
  Issues: https://${repository.issuesUrl}

  Sitemap Protocol: https://www.sitemaps.org/protocol.html
  Google Guide: https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap
  XML Format: UTF-8 encoding, max 50MB uncompressed, max 50,000 URLs per file
-->`;
}

module.exports = {
  PROJECT_CONFIG,
  getCopyrightNotice,
  getProjectTitle,
  getRepositoryUrl,
  getSupportUrl,
  getGenerationComment,
  getXmlGenerationHeader,
};
